# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 Ui code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiAddEditForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(333, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 211, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.lineEdit_title = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.verticalLayout.addWidget(self.lineEdit_title)
        self.roast = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.roast.setObjectName("roast")
        self.verticalLayout.addWidget(self.roast)
        self.lineEdit_roast = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_roast.setObjectName("lineEdit_roast")
        self.verticalLayout.addWidget(self.lineEdit_roast)
        self.label_type = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_type.setObjectName("label_type")
        self.verticalLayout.addWidget(self.label_type)
        self.lineEdit_type = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.verticalLayout.addWidget(self.lineEdit_type)
        self.label_descrip = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_descrip.setObjectName("label_descrip")
        self.verticalLayout.addWidget(self.label_descrip)
        self.lineEdit_descrip = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_descrip.setObjectName("lineEdit_descrip")
        self.verticalLayout.addWidget(self.lineEdit_descrip)
        self.label_price = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_price.setObjectName("label_price")
        self.verticalLayout.addWidget(self.label_price)
        self.lineEdit_price = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.verticalLayout.addWidget(self.lineEdit_price)
        self.label_volume = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_volume.setObjectName("label_volume")
        self.verticalLayout.addWidget(self.label_volume)
        self.lineEdit_volume = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_volume.setObjectName("lineEdit_volume")
        self.verticalLayout.addWidget(self.lineEdit_volume)
        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(60, 500, 75, 23))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(160, 500, 75, 23))
        self.btn_cancel.setObjectName("btn_cancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Название"))
        self.roast.setText(_translate("MainWindow", "Прожарка"))
        self.label_type.setText(_translate("MainWindow", "Тип"))
        self.label_descrip.setText(_translate("MainWindow", "Описание"))
        self.label_price.setText(_translate("MainWindow", "Цена"))
        self.label_volume.setText(_translate("MainWindow", "Объём"))
        self.btn_ok.setText(_translate("MainWindow", "ОК"))
        self.btn_cancel.setText(_translate("MainWindow", "Отмена"))
